# Generated by Django 6.0.7 on 2026-07-12 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgstructure", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                ("acquisition_date", models.DateField()),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Damaged", "Damaged"),
                        ],
                        default="New",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Allocated", "Allocated"),
                            ("Reserved", "Reserved"),
                            ("Under Maintenance", "Under Maintenance"),
                            ("Lost", "Lost"),
                            ("Retired", "Retired"),
                            ("Disposed", "Disposed"),
                        ],
                        default="Available",
                        max_length=30,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("is_bookable", models.BooleanField(default=False)),
                ("qr_code", models.CharField(blank=True, max_length=255, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="assets/photos/"
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="assets/docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="orgstructure.assetcategory",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orgstructure.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetAllocationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_at", models.DateTimeField(auto_now_add=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "allocated_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_history",
                        to="asset_manager.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetMaintenanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue", models.TextField()),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_history",
                        to="asset_manager.asset",
                    ),
                ),
            ],
        ),
    ]
